### ISSUE TITLE
Database error "duplicate key value violates unique constraint "user_status_uid_ix" " after migrating to Nextcloud AIO

### ISSUE THREAD

**Issue by C11235** [nextcloud/all-in-one#4220] opened 2024-02-15 08:32 UTC
### Steps to reproduce
1. Migrate both files and database from the native Nextcloud installation to Nextcloud Docker AIO using the official documentation
2. Open the Nextcloud AIO database container log
3. Notice the error

### Expected behavior 
There should be no error.

### Actual behavior 
Everything seems to work, but this error is logged frequently:
2024-02-15 09:02:24.138 CET [6327] ERROR:  duplicate key value violates unique constraint "user_status_uid_ix"
2024-02-15 09:02:24.138 CET [6327] DETAIL:  Key (user_id)=(_clemens) already exists.
2024-02-15 09:02:24.138 CET [6327] STATEMENT:  UPDATE "oc_user_status" SET "is_backup" = $1, "user_id" = $2 WHERE "user_id" = $3

### Host OS 
Ubuntu 22.04.3 LTS

#### Nextcloud AIO version
Nextcloud AIO v7.11.2

#### Current channel 
latest

**Comment by szaimen** [comment] 2024-02-15 08:49
Duplicate of https://github.com/nextcloud/server/issues/42625

**Closed by szaimen** 2024-02-15 08:49 UTC
Labels: 0. Needs triage, bug
