### ISSUE TITLE
Make OnlyOffice work behind Nginx

### ISSUE THREAD

**Issue by Ondolin** [nextcloud/all-in-one#450] opened 2022-04-01 21:48 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. activate OnlyOffice in the AIO config
2. create a new document in Nextcloud

### Expected behaviour 
The OnlyOffice interface should open.

### Actual behaviour
There is an error: 

Web browser logs:

```
EvalError: Refused to create a WebAssembly object because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'nonce-V1V5WUxHRW41d3hQWXNRekROZWkrd0pLbXhtSG5wTG9pdWdlUVJLMGdBYz06RWlMS1lnZFhoVUI1TEpaUVliT2FqR29UMlNyU3p2VGI3STE1Q0hIRHozST0=' blob: https://**.**/onlyoffice/ 'unsafe-inline'".
```
```
Refused to connect to wss://**.**/onlyoffice/7.0.1-37/doc/3691662461/c/682/tnu0mff1/websocket because it appears in neither the connect-src directive nor the default-src directive of the Content Security Policy.
```

Docker logs:

```
https://*/onlyoffice/7.0.1-37/web-apps/vendor/sockjs/sockjs.min.js:2:19946
[2022-04-01T21:33:09.542] [ERROR] nodeJS - changesError: docId = 3691662461 Error: SecurityError: The operation is insecure. Script: https://*/onlyoffice/7.0.1-37/web-apps/vendor/sockjs/sockjs.min.js Line: 2:21103 userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15 platform: MacIntel isLoadFullApi: true isDocumentLoadComplete: false StackTrace: WebSocket@[native code]
@https://*/onlyoffice/7.0.1-37/web-apps/vendor/sockjs/sockjs.min.js:2:21103
```

### Host
Ubuntu + Nginx config

#### Nextcloud AIO version
0.9.1

**Comment by szaimen** [comment] 2022-05-03 20:36
Some question from my side:
Does setting the host value for the onlyoffice path to onlyoffice make it work?

Did not test this logic:
```
location /onlyoffice {
proxy_set_header Host $host/onlyoffice;
}
```

**Comment by Ondolin** [comment] 2022-05-03 21:12
Now it has two new errors inplace of the old ones:

```
Unrecognized Content-Security-Policy directive 'worker-src'.
```

```
Failed to load resource: the server responded with a status https://**/onlyoffice/web-apps/apps/api/documents/api.js of 404 ()
```

**Comment by szaimen** [comment] 2022-05-03 21:13
How does your config file look now?

**Comment by szaimen** [comment] 2022-05-03 21:15
Okay maybe 
```
location ^~ /onlyoffice {
proxy_set_header Host $host/onlyoffice;
}
```
Then?

**Comment by Ondolin** [comment] 2022-05-03 21:21
Still the same error.

My current config is:

```
# From https://www.nginx.com/blog/websocket-nginx/
map $http_upgrade $connection_upgrade {
    default Upgrade;
    ''      close;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    server_name cloud.**;

    location / {
        proxy_pass http://localhost:11000;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        # Websocket
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
    }

    location ^~ /onlyoffice {
	proxy_set_header Host $host/onlyoffice;
    }

    ssl_certificate /etc/letsencrypt/live/**-0003/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/**-0003/privkey.pem;
 # managed by Certbot
}
```

**Comment by szaimen** [comment] 2022-05-03 21:22
Hm...

**Comment by szaimen** [comment] 2022-05-03 21:24
Maybe move the block above the other block?

**Comment by Ondolin** [comment] 2022-05-03 21:24
I don't know if it helps (maybe it is meant to be so), but https://cloud.**/onlyoffice/ returns a 404 too

**Comment by szaimen** [comment] 2022-05-03 21:25
Does the onlyoffice container run?

**Comment by szaimen** [comment] 2022-05-03 21:25
> I don't know if it helps (maybe it is meant to be so), but https://cloud.**/onlyoffice/ returns a 404 too

I think it is indeed meant to be like this...

**Comment by szaimen** [comment] 2022-05-03 21:36
one location that should work is this one: `onlyoffice/welcome/win.html`

**Comment by szaimen** [comment] 2022-05-03 21:36
If that works there is probably something else not working...

**Comment by szaimen** [comment] 2022-05-03 21:47
So yeah seems like we need someone with good nginx knowledge to solve this problem. I don't have that unfortunately...

**Comment by szaimen** [comment] 2022-05-03 21:48
Bascially the root block should be used always and only the host header should be changed when opening the onlyoffice locatioin...

**Comment by ecmchow** [comment] 2022-05-15 06:49
I am able to load up the OnlyOffice iframe using the below nginx config without specifying the /onlyoffice block, IMHO non-HTTPS requests and the Content-Security-Policy is blocking the OnlyOffice from working.

```
location / {
        # Proxy main Nextcloud traffic
        proxy_pass http://localhost:11000;
        proxy_pass_request_headers on;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $http_host;
        
        # rewrite non-HTTPS Location header and hiding Content-Security-Policy to let Onlyoffice load files
        proxy_redirect http:// https://;
        proxy_hide_header Content-Security-Policy;

        # Websocket
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $http_connection;
        proxy_buffering off;
}
```

However it cannot load the document due to a non-HTTPS request by the OnlyOffice **sdk-all-min.js** which might to modify the config in Apache container?
 
 `Blocked loading mixed active content “http://my.domain/onlyoffice/cache/files/91819554/Editor.bin/Editor.bin?md5=***&expires=1655190996&filename=Editor.bin”`

**Comment by szaimen** [comment] 2022-05-15 09:45
Hello, thanks for your feedback!

This may be fixed with https://github.com/nextcloud/all-in-one/pull/634 as well in the next release

**Comment by szaimen** [comment] 2022-05-19 18:00
Hello, this might be fixed with 1.2.1 Beta.

**Comment by szaimen** [comment] 2022-05-24 07:58
1.2.1 stable is released. Can you please try if it works now?

**Comment by ecmchow** [comment] 2022-05-24 15:22
Confirmed working with the latest release, thanks for the fix!

**Comment by szaimen** [comment] 2022-05-24 15:27
Thanks for testing! Closing then :)

**Closed by szaimen** 2022-05-24 15:27 UTC
Labels: documentation, help wanted, needs info
