### ISSUE TITLE
non unicode characters in AIO backup log

### ISSUE THREAD

**Issue by MariusQuabeck** [nextcloud/all-in-one#342] opened 2022-03-11 02:43 UTC
Hi,

some lines in my AIO backup log (/api/docker/logs?id=nextcloud-aio-borgbackup) show weird characters in some lines after checking backup integrity like:

```
@�rifying data   7.06%
g �����@�data  14.18%
g data  21�����@�.30%
�@�ifying data  28.43%
g d�����@�ata  35.55%
g data  42.�����@�67%
��@�fying data  49.80%
g da�����@�ta  56.92%
g data  64.0�����@�4%
���@�ying data  71.17%
g dat�����@�a  78.29%
g data  85.41�����@�%
����@�ing data  92.54%
g data������VCheck finished successfully on 11.03.2022 - 02:27:41 (00 hours 01 minutes 34 seconds)
```

also I believe there is a typo in line 1 :)
`Checking the backup integity...`

**Comment by MariusQuabeck** [comment] 2022-03-11 02:46
also there is no visual feedback on the AIO page if that integrity check was successful or not, which is why I was looking at the log in the first place :)

**Comment by szaimen** [comment] 2022-03-11 08:22
> @�rifying data   7.06%
> g ������@�data  14.18%
> g data  21������@�.30%
> �@�ifying data  28.43%
> g d������@�ata  35.55%
> g data  42.������@�67%
> ��@�fying data  49.80%
> g da������@�ta  56.92%
> g data  64.0������@�4%
> ���@�ying data  71.17%
> g dat������@�a  78.29%
> g data  85.41������@�%
> ����@�ing data  92.54%
> g data�������VCheck finished successfully on 11.03.2022 - 02:27:41 (00 hours 01 minutes 34 seconds)

Hm... no idea. I cannot reproduce that.

> Checking the backup integity...

Right, will fix that, thanks!

> also there is no visual feedback on the AIO page if that integrity check was successful or not

are you sure?

![image](https://user-images.githubusercontent.com/42591237/157829696-f13fb6fa-2829-4c83-953e-9681fe58741b.png)

**Comment by szaimen** [comment] 2022-03-11 08:28
> > Checking the backup integity...
> 
> Right, will fix that, thanks!

fixed with https://github.com/nextcloud/all-in-one/commit/15a289e8203959072b40a621065343bc1473304f

**Closed** 2022-03-11 08:28 UTC
Labels: 2. developing

**Comment by MariusQuabeck** [comment] 2022-03-11 18:34
I can reproduce the unicode issue every time by checking backup integrity 🤷

I had to clear cache/cookies for the backup integrity visual feedback to appear :)
![image](https://user-images.githubusercontent.com/17063564/157930706-8c5d0411-6522-47cf-a010-949f072f594a.png)

**Comment by szaimen** [comment] 2022-03-11 18:46
> I can reproduce the unicode issue every time by checking backup integrity 🤷

Very strange... Maybe again an arm64 issue only issue? But wouldn't know why...



> I had to clear cache/cookies for the backup integrity visual feedback to appear :)

Hm... This should actually be server side rendered so no need to change cookies/cache... If it works now i guess it should be fine though👍
