### ISSUE TITLE
TLS Error

### ISSUE THREAD

**Issue by R7JANV1** [nextcloud/all-in-one#952] opened 2022-07-19 08:54 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Set up AIO instance completely
2. Website scanning with https://observatory.mozilla.org
3. the following error is displayed for the TLS category: This site uses an untrusted or invalid certificate.

### Host OS 
Ubuntu
#### Current channel 
latest
#### Other valuable info 
![grafik](https://user-images.githubusercontent.com/90777102/179709396-ada0595e-dd3b-4f39-a59e-5944b58e09bd.png)

Ports 443 TCP and 3478 TCP/UDP are open

**Comment by szaimen** [comment] 2022-07-19 14:56
Duplicate of https://github.com/mozilla/http-observatory-website/issues/263

**Closed by szaimen** 2022-07-19 14:56 UTC
Labels: 0. Needs triage, bug
