### ISSUE TITLE
Nextcloud AIO on first launch appears broken with autoplay blocked.

### ISSUE THREAD

**Issue by ctag** [nextcloud/all-in-one#5387] opened 2024-10-06 16:10 UTC
### Steps to reproduce
1. Install nextcloud AIO 29.0.7 on docker compose from scratch
2. Finish the setup on webpage, and click "Open your nextcloud"
3. After logging in with the default 'admin' account, the page appears to freeze or crash.

### Expected behavior 
If autoplay is blocked, can AIO detect this and not show a button-less white modal?

### Actual behavior 
The short into animation fails to play, leaving a white box on the page:
![Image](https://github.com/user-attachments/assets/26d92f71-bcdc-4b6f-a141-2597f722294e)

#### Host OS 
Debian LXC

#### Output of `sudo docker info`
```
root@docker:~# docker info
Client: Docker Engine - Community
 Version:    27.3.1
 Context:    default   
 Debug Mode: false
 Plugins:                                
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.17.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.7
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 27
  Running: 15
  Paused: 0
  Stopped: 12
 Images: 32
 Server Version: 27.3.1
 Storage Driver: overlay2
  Backing Filesystem: zfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7f7fdf5fed64eb6a7caf99b3e12efcf9d60e311c
 runc version: v1.1.14-0-g2c9f560
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.6.32-production+truenas
 Operating System: Debian GNU/Linux 12 (bookworm)
 OSType: linux
 Architecture: x86_64
 CPUs: 24
 Total Memory: 70.75GiB
 Name: docker
 ID: b738e2d5-da9c-47ed-9ea2-2d8cb806509d
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

#### Docker run command or docker-compose file that you used
Defaults from the installation guide docker-compose.

#### Other valuable info 
Tested on Firefox.
Clicking the icon in the URL bar and setting to "allow video and audio" then refreshing the page shows the animation correctly, but this is non-intuitive.

**Comment by szaimen** [comment] 2024-10-07 09:17
Hi, this is a duplicate of https://github.com/nextcloud/firstrunwizard/issues/1323

**Closed by szaimen** 2024-10-07 09:17 UTC
Labels: 0. Needs triage
