### ISSUE TITLE
Multiarch Docker

### ISSUE THREAD

**Issue by yarons** [nextcloud/all-in-one#184] opened 2022-01-29 23:10 UTC
Docker supports multiarchitecture build nowadays, which means you can upload several docker architecture variants for the same tag to Docker hub.

This can all be done using a well configured Docker's buildx.

I have a working example on my GH repo which uploads the multiarch artifact to ghcr.io instead of Docker hub:
https://github.com/yarons/pritunl-zero-docker/actions/runs/1736367592/workflow
https://github.com/yarons/pritunl-zero-docker/blob/main/.github/workflows/docker-image.yml

These are the actual artifacts (ready for pull in both architectures):
https://github.com/yarons?tab=packages&repo_name=pritunl-zero-docker

**Comment by szaimen** [comment] 2022-01-31 12:33
Hi, thanks for your idea! Unfortunately we cannot build multiarch images as we rely on the docker repository api which itself is not able to handle multiarch container images. See https://github.com/nextcloud/all-in-one/pull/42#issuecomment-986057315
So this is unfortunately a won't fix for the time being.

**Closed by szaimen** 2022-01-31 12:33 UTC

**Comment by yarons** [comment] 2022-01-31 12:51
@szaimen So how do you explain this? (Or am I missing something?)
https://hub.docker.com/_/mongo?tab=tags

**Comment by szaimen** [comment] 2022-01-31 13:30
Yes, docker hub is able to display multiarch images. I don't know if they implemented a custom, not documented api or how they are doing it. Feel free to investigate how you can retreive the checksums for multiarch images. See https://github.com/nextcloud/all-in-one/pull/42#issuecomment-986051622 for some initial steps

**Comment by szaimen** [comment] 2022-01-31 13:30
If you find a way, we may consider building multiarch images.

**Comment by yarons** [comment] 2022-01-31 13:44
@szaimen The pipelines in my GitHub are modified for ghcr but I can adapt these to Dockerhub (The original script was for Dockerhub but I prefer ghcr so I modified it), where are your pipelines running?

If we were to modify my pipelines all you need to do is to replace the name of the image to dockerhub instead of ghcr and login to Dockerhub (The username and password should be stored as Docker secrets), then run docker push,

**Comment by szaimen** [comment] 2022-01-31 13:46
Nope, that is not what I am talking about. Did you read the comments that I've linked to?

**Comment by szaimen** [comment] 2022-01-31 13:47
The problem is that we are not able to retreive the checksums of multiarch images via the docker repo api

**Comment by szaimen** [comment] 2022-01-31 13:47
I know that it is possible to create multiarch container images without much trouble

**Comment by yarons** [comment] 2022-01-31 14:10
I see but why do you care so much for the hashes? Docker is agile enough to pull the right image to the right hosting arch.

**Comment by szaimen** [comment] 2022-01-31 14:11
Because we need that in order to be able to judge if the containers are up-to-date or not ;)

**Comment by szaimen** [comment] 2022-01-31 14:13
See e.g. https://github.com/nextcloud/all-in-one/blob/4e852761d91a3bc764ef389906c27e9504a66259/php/src/Docker/DockerActionManager.php#L73

**Comment by yarons** [comment] 2022-01-31 14:15
I saw something about tag architecture in here, could that possibly help?
https://www.arthurkoziel.com/dockerhub-registry-api/
(List Tags section).

**Comment by szaimen** [comment] 2022-01-31 14:19
Thanks but that is kind of actually what we are doing already: see https://github.com/nextcloud/all-in-one/blob/4e852761d91a3bc764ef389906c27e9504a66259/php/src/Docker/DockerHubManager.php#L37-L45

So as I said: until you show me a way to get all needed hashes of multiarch images, this will not be implemented :)

**Comment by yarons** [comment] 2022-01-31 14:22
I see, it looks like although there's architecture field in his responsed I couldn't find that officially.

I'll get back to you if I'll find something, thanks.

**Comment by szaimen** [comment] 2022-01-31 14:23
Thank you, too! :)

**Comment by yarons** [comment] 2022-01-31 14:35
I think I found something, run the following command on your machine and loot at the output:
docker manifest inspect --verbose library/ubuntu:latest

There must be a way, I'll try to see if I can get some documentation for it but I can definitely see multiarch hashes.
