### ISSUE TITLE
Logos disappear after update to NC 25

### ISSUE THREAD

**Issue by gbertolottiKS** [nextcloud/all-in-one#1661] opened 2023-01-03 08:17 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. update the instance to NC 25
2. done 

### Expected behavior 
The logos are shown as usual

### Actual behavior 
After the upgrade, the logo, the header one and the favicon disappeared.

### Host OS 
Ubuntu 22.04

#### Nextcloud AIO version 
4.0.1

#### Current channel 
latest

#### Other valuable info 
It's a very non-critical bug: to solve it, it just needs to re-set from the admin settings the above information.

**Comment by szaimen** [comment] 2023-01-03 08:22
Hi, thanks for the report. This is unfortunately a known issue and a duplicate of https://github.com/nextcloud/server/issues/35871

**Closed by szaimen** 2023-01-03 08:22 UTC
Labels: 0. Needs triage, bug
