### ISSUE TITLE
Container Notify Push won't start

### ISSUE THREAD

**Issue by marcatsmci** [nextcloud/all-in-one#3740] opened 2023-11-14 10:08 UTC
### Steps to reproduce
1. stop containers
2. start containers
3. wait
4. error in log 
5. container won't start

### Expected behavior 
Container up & running
### Actual behavior 

Error in log : 
`/start.sh: line 51: /nextcloud/custom_apps/notify_push/bin/x86_64/notify_push: Permission denied`

![image](https://github.com/nextcloud/all-in-one/assets/47881838/cb83abaa-3a41-4b95-b7e6-de3a61fe0a75)

### Host OS 
Linux <hostname> 5.10.0-26-amd64 #1 SMP Debian 5.10.197-1 (2023-09-29) x86_64 GNU/Linux

#### Nextcloud AIO version 
Nextcloud AIO v7.6.2

#### Current channel 
Latest

#### Other valuable info 
Nextcloud has been working fine for several weeks without any change
Behind nginx proxy

**Comment by CSDUMMI** [comment] 2023-11-14 10:28
This appears to be the same issue as with mine #3741

**Comment by MrEddX** [comment] 2023-11-14 18:34
I'm in the same situation.

**Comment by jospoortvliet** [comment] 2023-11-15 02:07
duplicate of https://github.com/nextcloud/all-in-one/issues/3727 - has been fixed already, coming in next release.

**Comment by jospoortvliet** [comment] 2023-11-15 02:08
(please do check for existing issues when reporting a problem, that saves the maintainer time that's better spend on fixing problems rather than de-duplicating github issues)

**Closed by jospoortvliet** 2023-11-15 02:07 UTC
Labels: 0. Needs triage, bug

**Comment by marcatsmci** [comment] 2023-11-15 08:17
Sorry !

**Comment by szaimen** [comment] 2023-11-16 16:59
This is now fixed with 7.7.0 Beta. Testing and feedback is welcome! See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel
