### ISSUE TITLE
User Account / Profile Avatar Initials not generated post Nextcloud 25 upgrade

### ISSUE THREAD

**Issue by tquest1** [nextcloud/all-in-one#1606] opened 2022-12-27 08:05 UTC
After upgrading to Nextcloud 25 on v3.2.0 & also on latest v4.0.1 Beta account avatar initials are not being generated as was the case prior to NC 25 on AIO. I have spun up a normal NC25 non-AIO, non-docker in a container & the initials are generated.

The Profile Picture is blank with a very tiny icons in the place that the initials should be, so I'm presuming that it may be a missing font?:

![user-profile-problem](https://user-images.githubusercontent.com/43093959/209633245-fa886302-2a24-49b5-8696-e412a7d0497d.png)

**Comment by szaimen** [comment] 2022-12-27 10:30
Hi, I fear this is a duplicate of https://github.com/nextcloud/server/issues/34755. And since Nextcloud comes with its own font file I dont think that this is a font issue: https://github.com/nextcloud/server/blob/20ea9a25353129b56d46951fe7d23939665ab2b2/lib/private/Avatar/Avatar.php#L133

**Closed by szaimen** 2022-12-27 10:30 UTC
