### ISSUE TITLE
DOCUMENT: Height adjustment of rows at inserted table 

### ISSUE THREAD

**Issue by 2II3** [nextcloud/all-in-one#5080] opened 2024-08-01 16:56 UTC
double to: [DOCUMENT: Height adjustment of rows at inserted table #9685](https://github.com/CollaboraOnline/online/issues/9685)

Describe the Bug
The height of a row is unable to be adjusted by the user. The Help-Guide is not helpful for this problem.

Steps to Reproduce
Create a new Document
Insert a table
Try to adjust the height of row.
Expected Behavior
The row should adjust to the new height.

Actual Behavior
Nothing happens.

https://github.com/user-attachments/assets/482858c2-4f1d-46c9-8e4e-b6975d412682

**Comment by szaimen** [comment] 2024-08-01 17:01
Duplicate of https://github.com/CollaboraOnline/online/issues/9685

**Closed by szaimen** 2024-08-01 17:01 UTC
Labels: 0. Needs triage, bug

**Comment by 2II3** [comment] 2024-08-01 17:03
@szaimen closed as complete is wrong.😔
