### ISSUE TITLE
Can't move folders from NC AIO internal storage to external storage 

### ISSUE THREAD

**Issue by securegh** [nextcloud/all-in-one#1306] opened 2022-10-24 19:29 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Mounting external storage using  `-e NEXTCLOUD_MOUNT="/mnt/data/"`
2. Setting rwx permissions for www-data account on /mnt/data/
3. Setting external storage inside NC,

### Expected behavior 
I am able to create/delete folders/ files and move/copy files from NC internal storage to external storage.    

### Actual behavior 
I am not able to move  **folders** from NC internal storage to external storage. 
 
### Host OS 
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"

#### Nextcloud AIO version 
24.0.6

#### Current channel 
Nextcloud AIO v2.0.4
You are running the [latest-arm64](https://github.com/nextcloud/all-in-one#how-to-switch-the-channel) channel.

**Comment by szaimen** [comment] 2022-10-24 19:37
Hi, can you post your Nextcloud logs here?

**Comment by securegh** [comment] 2022-10-24 21:43
> Hi, can you post your Nextcloud logs here?

https://gist.github.com/securegh/1ee0553a0e4fdd568698e671d25b27e4


Thank you for looking into this!

**Comment by szaimen** [comment] 2022-10-24 22:00
Duplicate of https://github.com/nextcloud/server/issues/14743

**Closed by szaimen** 2022-10-24 22:00 UTC
Labels: 0. Needs triage, bug, needs info
