### ISSUE TITLE
Broken workflow : PHP Deprecation Detector

### ISSUE THREAD

**Issue by docjyJ** [nextcloud/all-in-one#5053] opened 2024-07-26 20:22 UTC
### Steps to reproduce
1. Run PHP Deprecation Detector
2. See log section run script : https://github.com/nextcloud/all-in-one/actions/runs/10091050077/job/27901771852
3. See log section run script : https://github.com/nextcloud/all-in-one/actions/runs/10114167728/job/27972198686

### Expected behavior 
Say no deprecation, I guess.

### Actual behavior 
Say :

`Target version is not valid. Available target versions: 5.3, 5.4, 5.5, 5.6, 7.0, 7.1, 7.2, 7.3, 7.4, 8.0, 8.1`

`Script phpdd scan -n -t 8.3 src/*.php src/**/*.php public/index.php handling the php-deprecation-detector event returned with error code 1`

### Host OS 
github

#### Nextcloud AIO version 
29

#### Current channel 
Main branch

#### Other valuable info 
https://github.com/wapmorgan/PhpDeprecationDetector/blob/master/src%2FPhpCodeFixer.php#L14

**Comment by szaimen** [comment] 2024-07-27 08:14
Hi, thanks for bringing this up! The problem is that the upstream tool does not have rules for php 8.3 yet. My hope is that they will ship it at some point and then make the workflow work as expected. Until then the following logic is in place: https://github.com/nextcloud/all-in-one/blob/73e4ea26ab6f5f14ec64a8f2b1f9678f434bfcc9/.github/workflows/php-deprecation-detector.yml#L32-L35

**Comment by szaimen** [comment] 2024-07-27 08:14
What wouls you say how should we proceed with this?

**Comment by docjyJ** [comment] 2024-07-27 09:32
Yes, until the library is updated, it is impossible to do anything.

**Comment by szaimen** [comment] 2024-07-27 11:48
So shall we close this issue as it is unactable?

**Comment by docjyJ** [comment] 2024-07-27 12:38
Yes or set the label `blocked` so as not to forget.

As you wish!

**Comment by szaimen** [comment] 2024-07-27 13:04
Lets close this then for now

**Closed by szaimen** 2024-07-27 13:04 UTC
Labels: 0. Needs triage, bug, low, dependencies
